### ISSUE TITLE
EntAI 1.0코드를 참고해도 되나요?

### ISSUE THREAD

**Issue by avocad5** [muno9748/Ent3D#1]
EntAI에도 이슈를 남겼는데 못보신것같아서 여기에도 올립니다

EntAI 1.0버전의 코드를 참고해서 비공식블록을 만들려고합니다
다 베낀다는게 아니고 3~13번째줄 까지의 코드를 참고하는것입니다
muno님께 허락을 맡아야할것같아서... 혹시 EntAI 1.0코드를 참고해서 비공식블록을 만들어도되나요?

**Comment by muno9748** [comment]
네 가능합니다
이용해주시면 저야 고맙죠

**Comment by muno9748** [comment]
허락 굳이 안맡아도 되고 muno님의 코드를 참고했다고만 써놓으시면 됩니다

**Comment by avocad5** [comment]
감사합니다!
