### ISSUE TITLE
[!] 기능 제안

### ISSUE THREAD

**Issue by muno9748** [muno9748/Ent3D#2]
이 프로젝트는 EntLibrary 2.0을 기반으로 해서 만들건데
도형, 빛, 물리(2.0에 추가예정), Pointer-Lock-Control 등은 기본적으로 지원한 예정입니다
더 필요하다고 생각되는 기능이 있으면 써주세요

**Comment by genius0412** [comment]
빛을 추가한다는건 그림자도 저절로 된다는 건가요?

**Comment by muno9748** [comment]
그림자를 보이게할지 안보이게할지 설정하는 코드가 추가될거에요

**Comment by avocad5** [comment]
좌표계가 엔트리좌표계하고 달라서 익숙하지가 않아요. 그래서 x축 y축 z축 을 표시하면 좋을것같아요

**Comment by muno9748** [comment]
네
